### ISSUE TITLE
Cannot start songs by clicking on them in songs view and artist top tracks

### ISSUE THREAD

**Issue by tlaundal** [dirkgroenen/mopidy-mopify#62] opened 2015-02-25 17:57 UTC
When I open the songs view/my collection of songs, I cannot click on the tracks in the list to start them.
It doesn't work to use the "Play track" option in the right-click menu either. Adding to queue from the right-click menu works, though.

I experience the same problems on the artist pages with the list of the artist's top songs, and in the play queue, but not in playlists, or whole albums.

EDIT: It seems this is not always reproducible. I cannot seem to find a pattern on why this happens. Sometimes I have this problems on all songs in those lists, other times only on certain songs.

**Comment by totokaka** [comment] 2015-02-25 18:12
I found this error in the developer console, I think it's related:
![x4yjmbd](https://cloud.githubusercontent.com/assets/817001/6377084/2e322618-bd22-11e4-92fa-fd2068be292d.png)


```
18:54:27.954 "Unexpected response received. Message was:" Object { jsonrpc: "2.0", id: 25, result: 0 }                         mopidy-mopify-1.3.1.js:33
18:55:51.997 "Server returned error:" Object { message: "Application error", code: 0, data: Object }                           mopidy-mopify-1.3.1.js:33
18:55:51.998 "Potentially unhandled rejection [1] [21]<@http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:29727
              e@http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7694
              b@http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7869
              @http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:1
              @http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7454
              @http://localhost:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:1
"                                                                                                                              mopidy-mopify-1.3.1.js:32
[15]</</</</k<()                                                                                                               mopidy-mopify-1.3.1.js:32
d()                                                                                                                            mopidy-mopify-1.3.1.js:32
j()                                                                                                                            mopidy-mopify-1.3.1.js:32

18:55:57.212 "Server returned error:" Object { message: "Application error", code: 0, data: Object }                           mopidy-mopify-1.3.1.js:33
```

**Comment by dirkgroenen** [comment] 2015-02-25 20:56
Werd, but I'll look into it tomorrow and check if it happens for me too. Hopefully I can reproduce it and find the reason.

**Comment by dirkgroenen** [comment] 2015-02-26 09:10
Do you have a big list of Spotify songs? Since the songs aren't returned by Mopidy we have to lookup all track in the library before adding them to the tracklist. At the moment I have about 150 tracks in my collection, running on a fast computer, but it still takes a few seconds to play.

Does it respond when you select multiple track (hold down CTRL and click on the tracks) and play them via the context menu?

**Comment by totokaka** [comment] 2015-02-26 14:22
Yes, you are completely correct.

My collection includes a lot of songs (probably around 3000+). I see the time it takes to start playing increases when I load more songs  in the list (scrolling down). Selecting two songs and just playing those works much faster, as you predicted.

**Comment by dirkgroenen** [comment] 2015-02-26 15:22
I've opened an issue in Mopidy's repo and their answer is that a new method will be added in the new Core API version. Which brings us at no good solution for this issue at the moment.

Normally when clicking on a track it should add all tracks, not the visible one (which is happening now). I have fixed that issue in the development branch and will release it soon. At the same time I will be thinking about a way on how to temporarily solve or bypass this problem.

**Comment by totokaka** [comment] 2015-02-26 15:35
I just experienced this issue in an album (12 songs), but after a complete refresh(Ctrl+Shift+R), it worked instantly. I didn't bother waiting more the a couple of seconds before I did the refresh, so I can't be sure if this was the same issue.

**Comment by dirkgroenen** [comment] 2015-02-27 12:41
Did it happen once or every time?

**Comment by totokaka** [comment] 2015-02-27 13:10
It is not consistent. Right now it works flawlessly. I will try again after having Mopify running for a few hours. I have a feeling this has to do with how long Mopify has been playing songs.

**Comment by dirkgroenen** [comment] 2015-02-27 14:18
Would you also be so kind to check your browser's memory when it doesn't work? Might be somehow related to issue #61..

**Comment by 5paceManSpiff** [comment] 2015-02-27 22:46
This is happening to me as well, and I currently have about 500 songs in my playlist.  It doesn't appear to be related to the momory error found in #61.

**Comment by totokaka** [comment] 2015-02-28 08:13
So, I've had mopify open for almost 20 hours, listening to music for the first five. The memory consumption of Firefox is now 745 MiB, I'll see how much it is at first when I start Firefox.

Playing a song from the Songs view takes a bit of time before it starts, but playing from an album is quite responsive.

**Comment by dirkgroenen** [comment] 2015-02-28 13:36
When you want to play a "custom tracklist" (like top tracks from an artist or your song collection) Mopify has to lookup all the tracks in mopidy's library. This process takes quite some time when more tracks are selected. At the moment there isn't a good fix for this problem. 

I don't think those extra 745 are all from Mopify and unfortunately it's hard to find out, since FireFox doesn't have a chrome-like task manager.

**Comment by totokaka** [comment] 2015-03-01 15:55
I've got an error for you. I wasn't able to start any songs from the top list of an artist, each time I clicked a song, this error popped up in the console:
![](http://i.imgur.com/LUcMLLo.png)

This is the text in the box:
```
<anonymous> mopidy-mopify-1.3.1.js:22
i() mopidy-mopify-1.3.1.js:11
j/<() mopidy-mopify-1.3.1.js:11
Vc/this.$get</l.prototype.$eval() mopidy-mopify-1.3.1.js:11
Vc/this.$get</l.prototype.$digest() mopidy-mopify-1.3.1.js:11
Vc/this.$get</l.prototype.$evalAsync/<() mopidy-mopify-1.3.1.js:11
g() mopidy-mopify-1.3.1.js:10
Vb/n.defer/c<() mopidy-mopify-1.3.1.js:10
```

I think this issue is really multiple bugs/problems that are hard to separate.

**Comment by dirkgroenen** [comment] 2015-03-02 09:55
Looks like all these problems are related to starting tracks which aren't loaded through Mopidy. I might need to check that code. 

Does it also produce Mopidy errors?

**Comment by totokaka** [comment] 2015-03-02 14:12
I see no errors in the logs of Mopidy. The error was reproducible after a restart of the whole machine.
The error seems to be universal for all artists: *I cannot start any songs from the top list of an artist*

**Comment by dirkgroenen** [comment] 2015-03-26 16:30
With the release of Mopidy 1.0 I can now lookup multiple tracks, which should fix this issue. 

I will read through the complete changelog and change everything so it's compatible with Mopidy's new version.

**Comment by dirkgroenen** [comment] 2015-04-05 12:05
Despite Mopidy's new URI parameter it's still not possible to get this feature working as it should be. For now I've added a note on the page and I will move this issue to a next milestone.

**Comment by adamcik** [comment] 2015-05-19 20:10
So if understand the problem right it's the fact that we are doing lookups of all the URIs against the backend that kills things. This wouldn't surprise me as sadly we forgot to add a `lookup(uris)` to the backends, so we have to do a roundtrip to the backends for each and every uri to expand it to tracks... :/

**Comment by dirkgroenen** [comment] 2015-05-19 21:31
It indeed looks/sounds like that's the thing which causes the lag. I'm not so familiar with the Mopidy backends, so the following might be bullshit, but why should it be possible to add playlists with thousands of tracks at the same time? 

I have been thinking about creating some sort of 'hidden' playlist which synchronizes with the Spotify Songs library, but that feels like a huge ass hack.

**Comment by adamcik** [comment] 2015-05-19 21:45
Currently tracklist add doesn't really have any limitations to how much you can add at a time, but with this issue in mind we might consider setting an upper limit forcing clients to batch things. That is if we can't make this work reliably for "large" users.

Workaround I would try for now is just trying to batch the URIs to add into say 100 URI chuncks, should help keep the time things block shorter, and other things like starting to play don't have to wait for all the tracks to load.

**Comment by dirkgroenen** [comment] 2015-05-19 21:52
Already using the implementation of batching tracks for the Station/Radio feature, but to be honest that's far from ideal for this case. Reading your opinion it's not worthy/possible to change the backend so this won't be a problem?

**Comment by adamcik** [comment] 2015-05-19 21:59
I want to change the backends, the problem is that it would be a breaking API change which we can't do in a 1.x release. So we either have to wait for 2.x, or jump ahead to it, or add a function to the backends base class that has a shim that calls the old code.

Likely the latter option is the way to go. It would save us all the thread switches and back and forth, and backends that can be smarter about things can override the new function to handle multiple URIs directly.

**Comment by dirkgroenen** [comment] 2015-05-19 22:03
Alright, clear! You definitely dropping a valid point about the limitations of API breaking changes in 1.x.x. I'll wait patiently.

**Closed** 2020-04-13 16:57 UTC
Labels: enhancement, prio, service, wontfix
